apiVersion: v1
kind: Secret
metadata:
  name: tls-ca
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: generic
data:
  cacerts.pem: {{ .Values.caCert | b64enc | indent 4 }}
