apiVersion: v2
name: external-dns
type: application
version: 1.20.0
appVersion: "0.20.0"

dependencies:
  - name: external-dns
    version: 1.20.0
    repository: https://kubernetes-sigs.github.io/external-dns
    alias: external-dns
