external-dns:
  provider:
    name: pihole
  env:
    - name: EXTERNAL_DNS_PIHOLE_API_VERSION
      value: "6"
    - name: EXTERNAL_DNS_PIHOLE_SERVER
      value: "https://dns-01.dev.tung.trankim.net"
    - name: EXTERNAL_DNS_PIHOLE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pihole-password
          key: EXTERNAL_DNS_PIHOLE_PASSWORD
  registry: noop
  domainFilters:
    - "rke2-01.k8s.tung.trankim.net"
  extraVolumeMounts:
    - name: ca-certificates
      mountPath: /etc/ssl/certs/ca-certificates.crt
      subPath: ca-certificates.crt
      readOnly: false
  extraVolumes:
    - name: ca-certificates
      configMap:
        name: ca-certificates
