apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: private-ca
spec:
  acme:
    server: https://ca.home.trankim.net/acme/acme/directory
    email: cert-manager@home.trankim.net
    privateKeySecretRef:
      name: private-ca-secret
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ3VENDQVdhZ0F3SUJBZ0lSQUp6Znlmc1N6Zi9MUkE4Y00wNHlBdUV3Q2dZSUtvWkl6ajBFQXdJd1BqRVoKTUJjR0ExVUVDaE1RVkhKaGJpQkxhVzBnVG1WMGQyOXlhekVoTUI4R0ExVUVBeE1ZVkhKaGJpQkxhVzBnVG1WMApkMjl5YXlCU2IyOTBJRU5CTUI0WERUSTFNVEV5TWpBNU16UXlOVm9YRFRNMU1URXlNREE1TXpReU5Wb3dQakVaCk1CY0dBMVVFQ2hNUVZISmhiaUJMYVcwZ1RtVjBkMjl5YXpFaE1COEdBMVVFQXhNWVZISmhiaUJMYVcwZ1RtVjAKZDI5eWF5QlNiMjkwSUVOQk1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRVR4V2duYmowUVpOUwo3bitybUc0MExmT1BpQXpaeVlLak9vaER0MHN4OFJweXZCVVpRTGRZeFhnY0FQOVE4OHdGNng3K0RYK1R4SFV3ClZxTWJZKzlKamFORk1FTXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRRXcKSFFZRFZSME9CQllFRkluZU95Tm5HTlIzL2RZK211elNiWW50NFBRYU1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQwpJUUQ5eTZBalhRamZPK2hqZUVuUHNnalF5Z1VIRkNoS0JWR0N6OTh5SUVGZWdBSWhBTnBOaTNFb3htTmRJZTFPCkgzb0o5VUFxQVQxbE5VT3gvaXBuSmpjOUh6VzcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
