apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: trust-bundle
spec:
  sources:
    - useDefaultCAs: true
    - inLine: |-
        -----BEGIN CERTIFICATE-----
        MIIBwTCCAWagAwIBAgIRAJzfyfsSzf/LRA8cM04yAuEwCgYIKoZIzj0EAwIwPjEZ
        MBcGA1UEChMQVHJhbiBLaW0gTmV0d29yazEhMB8GA1UEAxMYVHJhbiBLaW0gTmV0
        d29yayBSb290IENBMB4XDTI1MTEyMjA5MzQyNVoXDTM1MTEyMDA5MzQyNVowPjEZ
        MBcGA1UEChMQVHJhbiBLaW0gTmV0d29yazEhMB8GA1UEAxMYVHJhbiBLaW0gTmV0
        d29yayBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAETxWgnbj0QZNS
        7n+rmG40LfOPiAzZyYKjOohDt0sx8RpyvBUZQLdYxXgcAP9Q88wF6x7+DX+TxHUw
        VqMbY+9JjaNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEw
        HQYDVR0OBBYEFIneOyNnGNR3/dY+muzSbYnt4PQaMAoGCCqGSM49BAMCA0kAMEYC
        IQD9y6AjXQjfO+hjeEnPsgjQygUHFChKBVGCz98yIEFegAIhANpNi3EoxmNdIe1O
        H3oJ9UAqAT1lNUOx/ipnJjc9HzW7
        -----END CERTIFICATE-----
  target:
    configMap:
      key: "trust-bundle.pem"
