apiVersion: v2
name: traefik
type: application
version: 37.4.0
appVersion: "v37.4.0"

dependencies:
  - name: traefik
    version: 37.4.0
    repository: https://traefik.github.io/charts
    alias: traefik
