apiVersion: v2
name: traefik
type: application
version: 1.19.1
appVersion: "v1.19.1"

dependencies:
  - name: traefik
    version: 37.4.0
    repository: https://traefik.github.io/charts
    alias: traefik
