apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - home-assistant.tung.trankim.net
      secretName: home-assistant-tls
  rules:
    - host: home-assistant.tung.trankim.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 443
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: home-assistant-transport
spec:
  rootCAs:
    - secret: ca-certificates
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: {{ .Release.Namespace }}-home-assistant-transport@kubernetescrd
    traefik.ingress.kubernetes.io/service.passhostheader: "false"
spec:
  type: ExternalName
  externalName: home-assistant.dev.tung.trankim.net
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
