{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    server: {{ .Values.clusterIssuer.acme.server | quote }}
    email: {{ .Values.clusterIssuer.acme.email | quote }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.name }}-secret
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
    caBundle: {{ .Values.clusterIssuer.caBundle | quote }}
{{- end }}
