apiVersion: v2
name: cert-manager
type: application
version: 1.19.1
appVersion: "v1.19.1"

dependencies:
  - name: cert-manager
    version: v1.19.1
    repository: oci://quay.io/jetstack/charts
    alias: cert-manager
