- name: Disable ufw
  systemd:
    name: ufw
    state: stopped
    enabled: no

- name: Disable swap
  ansible.builtin.shell: |
    swapoff -a
    sed -i.bak '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Enable required kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - br_netfilter
    - overlay

- name: Ensure kernel modules are loaded on boot
  copy:
    content: |
      br_netfilter
      overlay
    dest: /etc/modules-load.d/rke2.conf
    owner: root
    group: root
    mode: '0644'

- name: Set sysctl parameters for RKE2
  copy:
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
      vm.overcommit_memory                = 1
      kernel.panic                        = 10
      kernel.panic_on_oops                = 1
    dest: /etc/sysctl.d/99-rke2.conf
    owner: root
    group: root
    mode: '0644'

- name: Apply sysctl parameters
  command: sysctl --system

- name: Create group for etcd
  group:
    name: etcd
    state: present
    system: yes

- name: Create user for etcd
  user:
    name: etcd
    group: etcd
    system: yes
    create_home: no
    shell: /sbin/nologin

- name: Install required packages
  apt:
    name:
      - nfs-common
    state: present
