apiVersion: v2
name: rancher
description: ""
type: application
version: 2.13.0
appVersion: "2.13.0"

dependencies:
  - name: rancher
    version: 2.13.0
    repository: https://releases.rancher.com/server-charts/stable
